 * Serving Flask app "flaskr" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 854-962-326
192.168.0.101 - - [15/Mar/2020 23:19:58] "GET / HTTP/1.1" 200 -
192.168.0.101 - - [15/Mar/2020 23:19:58] "GET /static/style.css HTTP/1.1" 200 -
192.168.0.101 - - [15/Mar/2020 23:19:58] "GET /favicon.ico HTTP/1.1" 404 -
192.168.0.101 - - [15/Mar/2020 23:20:02] "GET /auth/register HTTP/1.1" 200 -
192.168.0.101 - - [15/Mar/2020 23:20:02] "GET /favicon.ico HTTP/1.1" 404 -
192.168.0.101 - - [15/Mar/2020 23:20:09] "GET /auth/login HTTP/1.1" 200 -
192.168.0.101 - - [15/Mar/2020 23:20:09] "GET /favicon.ico HTTP/1.1" 404 -
192.168.0.101 - - [15/Mar/2020 23:20:17] "POST /auth/login HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/Public/myblog/flaskr/auth.py", line 58, in login
    session.clear()
  File "/usr/lib/python3/dist-packages/flask/sessions.py", line 101, in _fail
    raise RuntimeError('The session is unavailable because no secret '
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
192.168.0.101 - - [15/Mar/2020 23:20:18] "GET /auth/login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
192.168.0.101 - - [15/Mar/2020 23:20:18] "GET /auth/login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
192.168.0.101 - - [15/Mar/2020 23:20:18] "GET /auth/login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
192.168.0.101 - - [15/Mar/2020 23:20:18] "GET /auth/login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
192.168.0.101 - - [15/Mar/2020 23:20:18] "GET /auth/login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
192.168.0.108 - - [15/Mar/2020 23:21:01] "GET /auth/login HTTP/1.1" 200 -
127.0.0.1 - - [16/Mar/2020 13:25:44] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Mar/2020 13:25:58] "GET /blog HTTP/1.1" 404 -
127.0.0.1 - - [16/Mar/2020 13:28:47] "GET /blog/create HTTP/1.1" 404 -
127.0.0.1 - - [16/Mar/2020 13:28:55] "GET /blog/create.html HTTP/1.1" 404 -
127.0.0.1 - - [16/Mar/2020 13:30:00] "GET /create HTTP/1.1" 302 -
127.0.0.1 - - [16/Mar/2020 13:52:15] "GET / HTTP/1.1" 200 -
192.168.0.108 - - [17/Mar/2020 09:26:48] "GET /auth/login HTTP/1.1" 200 -
192.168.0.108 - - [17/Mar/2020 09:26:48] "GET /static/style.css HTTP/1.1" 304 -
192.168.0.108 - - [17/Mar/2020 09:26:48] "GET /favicon.ico HTTP/1.1" 404 -
192.168.0.108 - - [17/Mar/2020 09:31:09] "GET /auth/register HTTP/1.1" 200 -
192.168.0.108 - - [17/Mar/2020 09:31:11] "GET /auth/login HTTP/1.1" 200 -
192.168.0.108 - - [17/Mar/2020 09:31:16] "GET /index HTTP/1.1" 404 -
192.168.0.108 - - [17/Mar/2020 09:31:24] "GET / HTTP/1.1" 200 -
192.168.0.108 - - [17/Mar/2020 09:31:29] "GET /auth/register HTTP/1.1" 200 -
192.168.0.108 - - [17/Mar/2020 09:31:30] "GET /auth/login HTTP/1.1" 200 -
192.168.0.108 - - [17/Mar/2020 09:31:44] "GET /blog/create HTTP/1.1" 404 -
192.168.0.108 - - [17/Mar/2020 09:43:20] "GET /hello HTTP/1.1" 200 -
192.168.0.108 - - [17/Mar/2020 09:51:13] "GET /create HTTP/1.1" 302 -
192.168.0.108 - - [17/Mar/2020 09:51:13] "GET /auth/login HTTP/1.1" 200 -
192.168.0.108 - - [17/Mar/2020 09:51:19] "POST /auth/login HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/Public/myblog/flaskr/auth.py", line 58, in login
    session.clear()
  File "/usr/lib/python3/dist-packages/flask/sessions.py", line 101, in _fail
    raise RuntimeError('The session is unavailable because no secret '
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
192.168.0.108 - - [17/Mar/2020 09:51:19] "GET /auth/login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
192.168.0.108 - - [17/Mar/2020 09:51:19] "GET /auth/login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
192.168.0.108 - - [17/Mar/2020 09:51:20] "GET /auth/login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
192.168.0.108 - - [17/Mar/2020 09:51:20] "GET /auth/login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
192.168.0.108 - - [17/Mar/2020 09:51:20] "GET /auth/login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
192.168.0.108 - - [17/Mar/2020 09:51:34] "GET /create HTTP/1.1" 302 -
192.168.0.108 - - [17/Mar/2020 09:51:35] "GET /auth/login HTTP/1.1" 200 -
192.168.0.108 - - [17/Mar/2020 09:54:08] "GET /update HTTP/1.1" 404 -
192.168.0.108 - - [17/Mar/2020 09:58:06] "GET /auth/login HTTP/1.1" 200 -
192.168.0.108 - - [17/Mar/2020 09:58:13] "POST /auth/login HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/Public/myblog/flaskr/auth.py", line 58, in login
    session.clear()
  File "/usr/lib/python3/dist-packages/flask/sessions.py", line 101, in _fail
    raise RuntimeError('The session is unavailable because no secret '
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
192.168.0.108 - - [17/Mar/2020 09:58:13] "GET /auth/login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
192.168.0.108 - - [17/Mar/2020 09:58:13] "GET /auth/login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
192.168.0.108 - - [17/Mar/2020 09:58:14] "GET /auth/login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
192.168.0.108 - - [17/Mar/2020 09:58:14] "GET /auth/login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
192.168.0.108 - - [17/Mar/2020 09:58:14] "GET /auth/login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Serving Flask app "flaskr" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://0.0.0.0:12345/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 854-962-326
127.0.0.1 - - [27/Mar/2020 14:55:50] "GET /pac HTTP/1.1" 200 -
192.168.0.106 - - [27/Mar/2020 14:58:29] "GET / HTTP/1.1" 200 -
192.168.0.106 - - [27/Mar/2020 14:58:29] "GET /static/style.css HTTP/1.1" 404 -
192.168.0.106 - - [27/Mar/2020 14:58:30] "GET /favicon.ico HTTP/1.1" 404 -
192.168.0.106 - - [27/Mar/2020 14:58:44] "GET / HTTP/1.1" 200 -
192.168.0.106 - - [27/Mar/2020 14:58:44] "GET /static/style.css HTTP/1.1" 404 -
192.168.0.106 - - [27/Mar/2020 14:58:44] "GET /favicon.ico HTTP/1.1" 404 -
192.168.0.106 - - [27/Mar/2020 14:58:50] "GET / HTTP/1.1" 200 -
192.168.0.106 - - [27/Mar/2020 14:58:50] "GET /static/style.css HTTP/1.1" 404 -
192.168.0.106 - - [27/Mar/2020 14:58:56] "GET /pac HTTP/1.1" 200 -
192.168.0.106 - - [27/Mar/2020 14:58:56] "GET /favicon.ico HTTP/1.1" 404 -
192.168.0.106 - - [27/Mar/2020 14:59:05] "GET /pac HTTP/1.1" 200 -
192.168.0.106 - - [27/Mar/2020 14:59:06] "GET /pac HTTP/1.1" 200 -
192.168.0.106 - - [27/Mar/2020 15:03:03] "GET / HTTP/1.1" 200 -
192.168.0.106 - - [27/Mar/2020 15:03:03] "GET /static/style.css HTTP/1.1" 404 -
192.168.0.106 - - [27/Mar/2020 15:03:05] "GET /pac HTTP/1.1" 200 -
192.168.0.108 - - [28/Mar/2020 10:06:56] "GET / HTTP/1.1" 200 -
192.168.0.108 - - [28/Mar/2020 10:06:56] "GET /static/style.css HTTP/1.1" 404 -
192.168.0.108 - - [28/Mar/2020 10:06:56] "GET /favicon.ico HTTP/1.1" 404 -
192.168.0.108 - - [28/Mar/2020 10:53:25] "GET /auth/register HTTP/1.1" 200 -
192.168.0.108 - - [28/Mar/2020 10:53:25] "GET /static/style.css HTTP/1.1" 404 -
192.168.0.108 - - [28/Mar/2020 10:53:25] "GET /favicon.ico HTTP/1.1" 404 -
192.168.0.108 - - [28/Mar/2020 10:53:28] "GET /auth/login HTTP/1.1" 200 -
192.168.0.108 - - [28/Mar/2020 10:53:28] "GET /static/style.css HTTP/1.1" 404 -
192.168.0.103 - - [29/Mar/2020 11:36:56] "GET / HTTP/1.1" 200 -
192.168.0.103 - - [29/Mar/2020 11:36:56] "GET /static/style.css HTTP/1.1" 404 -
192.168.0.103 - - [29/Mar/2020 11:36:56] "GET /favicon.ico HTTP/1.1" 404 -
192.168.0.103 - - [29/Mar/2020 11:39:07] "GET / HTTP/1.1" 200 -
192.168.0.103 - - [29/Mar/2020 11:39:08] "GET /static/style.css HTTP/1.1" 404 -
192.168.0.103 - - [29/Mar/2020 11:39:52] "GET /pac HTTP/1.1" 200 -
192.168.0.108 - - [29/Mar/2020 15:44:32] "GET /static/style.css HTTP/1.1" 404 -
192.168.0.108 - - [29/Mar/2020 15:44:32] "GET /favicon.ico HTTP/1.1" 404 -
192.168.0.108 - - [29/Mar/2020 15:44:35] "GET / HTTP/1.1" 200 -
192.168.0.108 - - [29/Mar/2020 15:44:35] "GET /static/style.css HTTP/1.1" 404 -
192.168.0.108 - - [29/Mar/2020 15:44:38] "GET /auth/login HTTP/1.1" 200 -
192.168.0.108 - - [29/Mar/2020 15:44:38] "GET /static/style.css HTTP/1.1" 404 -
192.168.0.108 - - [29/Mar/2020 15:44:44] "POST /auth/login HTTP/1.1" 302 -
192.168.0.108 - - [29/Mar/2020 15:44:44] "GET / HTTP/1.1" 200 -
192.168.0.108 - - [29/Mar/2020 15:44:44] "GET /static/style.css HTTP/1.1" 404 -
192.168.0.108 - - [29/Mar/2020 15:46:03] "GET /create HTTP/1.1" 200 -
192.168.0.108 - - [29/Mar/2020 15:46:03] "GET /static/style.css HTTP/1.1" 404 -
127.0.0.1 - - [31/Mar/2020 19:32:20] code 400, message Bad request version ("UU8¬EÜÖæ²\x94Â\x7f\x01\x00>\x13\x02\x13\x03\x13\x01À,À0\x00\x9fÌ©Ì¨ÌªÀ+À/\x00\x9eÀ$À(\x00kÀ#À'\x00gÀ")
127.0.0.1 - - [31/Mar/2020 19:32:20] "  ü,,sÏ¾1£ß%ºQÀ÷Q0eÖ rèk{xÆÎé< Î2oÖµÆ4¶¬ù¦kûÎ¶UU8¬EÜÖæ²Â >À,À0 Ì©Ì¨ÌªÀ+À/ À$À( kÀ#À' gÀ" HTTPStatus.BAD_REQUEST -
192.168.0.108 - - [01/Apr/2020 10:53:03] "GET / HTTP/1.1" 200 -
192.168.0.108 - - [01/Apr/2020 10:53:04] "GET /static/style.css HTTP/1.1" 404 -
192.168.0.108 - - [01/Apr/2020 10:53:04] "GET /favicon.ico HTTP/1.1" 404 -
192.168.0.108 - - [01/Apr/2020 13:15:47] "GET / HTTP/1.1" 200 -
192.168.0.108 - - [01/Apr/2020 13:15:47] "GET /static/style.css HTTP/1.1" 404 -
192.168.0.108 - - [01/Apr/2020 13:15:47] "GET /favicon.ico HTTP/1.1" 404 -
192.168.0.108 - - [01/Apr/2020 13:15:48] "GET / HTTP/1.1" 200 -
192.168.0.108 - - [01/Apr/2020 13:15:48] "GET /static/style.css HTTP/1.1" 404 -
192.168.0.108 - - [01/Apr/2020 13:15:48] "GET / HTTP/1.1" 200 -
192.168.0.108 - - [01/Apr/2020 13:15:48] "GET /static/style.css HTTP/1.1" 404 -
192.168.0.108 - - [01/Apr/2020 13:15:48] "GET / HTTP/1.1" 200 -
192.168.0.108 - - [01/Apr/2020 13:15:48] "GET /static/style.css HTTP/1.1" 404 -
